post http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcmZlY3QiLCJpZCI6IjY1Yzg4NjY5ZjMxZWZkN2I0NWFlNWJhZSIsImlhdCI6MTcwNzY0NTEzNX0.1csit63XNbvWj_lUElE-Y1vnFbsBZGYCc3CQPYiDIuE

{
    "title": "request post middleware test, is awesome this tech!",
    "author": "stafillecokke",
    "url": "parfaitandre@gmail.com",
    "likes": 33
}

###
post http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "perfect",
    "name": "Andre",
    "password": "123@123"
}

###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "stacvirus"
}

# Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcmZlY3QiLCJpZCI6IjY1YzdhYjczOGMxMTk1Njg4NTY3YjI5OCIsImlhdCI6MTcwNzU4NDM5N30.KEoDYAo8NiCIS8QYilBPEEdJr0jLbQeiviSY1QrZIvM"
# perfect: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcmZlY3QiLCJpZCI6IjY1Yzg4NjY5ZjMxZWZkN2I0NWFlNWJhZSIsImlhdCI6MTcwNzY0NTEzNX0.1csit63XNbvWj_lUElE-Y1vnFbsBZGYCc3CQPYiDIuE
# root: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1Yzg4NGM2ODNlNTc2NGY5MjY4NWFlYyIsImlhdCI6MTcwNzY0MDI2NH0.blu89ogwk1KLu4Inb43co9hZ8UF2Xlrs-LpKWwRsRNY

