post http://localhost:3006/Blog/publications
Content-Type: application/json

{
    "title": "all girls are bitches!!",
    "author": "stac virus",
    "url": "parfaitandre@gmail.com",
    "likes": 20
}
###
get http://localhost:3006/Blog/publications